[project]
name = "activecampaign-mysql-bridge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.16.2",
    "email-validator>=2.2.0",
    "requests>=2.32.4",
    "schedule>=1.2.2",
]
