"""Description of your changes

Revision ID: e3c0d7d07d3f
Revises: 
Create Date: 2025-06-27 06:35:30.475072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e3c0d7d07d3f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maininfotable',
    sa.Column('maininfotableID', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('academic_program_dd', sa.String(length=20), nullable=True),
    sa.Column('accepted_date', sa.Date(), nullable=True),
    sa.Column('act_sat_dd', sa.String(length=2), nullable=True),
    sa.Column('address1_text', sa.String(length=150), nullable=True),
    sa.Column('address2_text', sa.String(length=150), nullable=True),
    sa.Column('admin_flag_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('admis_status_dd', sa.String(length=15), nullable=True),
    sa.Column('affidavit_of_support_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('alumni_text', sa.String(length=50), nullable=True),
    sa.Column('alumni_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=True),
    sa.Column('best_time_to_call_text', sa.String(length=20), nullable=True),
    sa.Column('church_referral_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('city_text', sa.String(length=30), nullable=True),
    sa.Column('date_entered', sa.Date(), nullable=True),
    sa.Column('date_of_birth_date', sa.Date(), nullable=True),
    sa.Column('denomination', sa.String(length=50), nullable=True),
    sa.Column('deposit_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('distance', sa.String(length=10), nullable=True),
    sa.Column('doctrine_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('email_text', sa.String(length=180), nullable=True),
    sa.Column('email_request_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('explain_info_text', sa.Text(), nullable=True),
    sa.Column('application_fee_dd', sa.String(length=3), nullable=True),
    sa.Column('feel_a_call_text', sa.String(length=40), nullable=True),
    sa.Column('finaid_rpt_sent_date', sa.Date(), nullable=True),
    sa.Column('first_name_text', sa.String(length=40), nullable=True),
    sa.Column('folder_location', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('funnel_location', sa.String(length=2), nullable=True),
    sa.Column('grad_date_numtext', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('health_form_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('hs_transcript_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('facebook_text', sa.String(length=250), nullable=True),
    sa.Column('international_student_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('isr_date', sa.Date(), nullable=True),
    sa.Column('isr_is_valid_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('kmbc_groups_dd', sa.String(length=35), nullable=True),
    sa.Column('lack_of_program_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('last_call_date', sa.Date(), nullable=True),
    sa.Column('last_contact_date', sa.Date(), nullable=True),
    sa.Column('last_email_date', sa.Date(), nullable=True),
    sa.Column('last_im_date', sa.Date(), nullable=True),
    sa.Column('last_letter_date', sa.Date(), nullable=True),
    sa.Column('last_name_text', sa.String(length=40), nullable=True),
    sa.Column('last_personal_visit_date', sa.Date(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.Column('letter_sent_date', sa.Date(), nullable=True),
    sa.Column('marital_status_dd', sa.String(length=2), nullable=True),
    sa.Column('medical_release_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('money_cb', sa.String(length=10), nullable=True),
    sa.Column('no_auto_email_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('non_traditional_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('number_of_visits_dd', sa.String(length=3), nullable=True),
    sa.Column('other_contact', sa.Text(), nullable=True),
    sa.Column('other_admin_text', sa.Text(), nullable=True),
    sa.Column('other_obstacle_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('pastor_church_text', sa.String(length=50), nullable=True),
    sa.Column('pastor_church_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('phone_text', sa.String(length=120), nullable=True),
    sa.Column('picture_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('post_hs_transcript_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('prospect_type', sa.String(length=2), nullable=True),
    sa.Column('provisional_acceptance_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('queue_action_dd', sa.String(length=20), nullable=True),
    sa.Column('rec_date_of_review_date', sa.Date(), nullable=True),
    sa.Column('recommendations_dd', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('rules_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('sch_app_rcvd_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('applied_semester_dd', sa.String(length=10), nullable=True),
    sa.Column('sex_dd', sa.String(length=2), nullable=True),
    sa.Column('special_interest_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('ss_number_text', sa.String(length=11), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('testimony_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('toefl_dd', sa.String(length=10), nullable=True),
    sa.Column('final_transcript_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('visit_1', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('visit_2', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('visit_3', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('visited_campus_date', sa.Date(), nullable=True),
    sa.Column('website_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('work_app', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('applied_year_text', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('zipcode', sa.String(length=10), nullable=True),
    sa.Column('groupcode_numtext', sa.String(length=20), nullable=True),
    sa.Column('instructions_text', sa.Text(), nullable=True),
    sa.Column('school_text', sa.String(length=150), nullable=True),
    sa.Column('downpayment_cb', sa.SmallInteger(), nullable=True),
    sa.Column('populi_id', mysql.INTEGER(), nullable=True),
    sa.Column('txt_optin_cb', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('primary_email_text', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('maininfotableID'),
    sa.UniqueConstraint('email_text')
    )
    op.alter_column('contactinfotable', 'notes',
               existing_type=mysql.VARCHAR(length=5000),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contactinfotable', 'notes',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=5000),
               existing_nullable=True)
    op.drop_table('maininfotable')
    # ### end Alembic commands ###
