from sqlalchemy import Column, String, Date, SmallInteger, Text
from sqlalchemy.dialects.mysql import BIGINT, INTEGER, TINYINT
from .db import Base

class MainInfoTable(Base):
    __tablename__ = "maininfotable"
    maininfotableID = Column(BIGINT(unsigned=True), primary_key=True, autoincrement=True)
    
    academic_program_dd = Column(String(20))
    accepted_date = Column(Date)
    act_sat_dd = Column(String(2))
    address1_text = Column(String(150))
    address2_text = Column(String(150))
    admin_flag_cb = Column(TINYINT(unsigned=True))
    admis_status_dd = Column(String(15))
    affidavit_of_support_cb = Column(TINYINT(unsigned=True))
    alumni_text = Column(String(50))
    alumni_cb = Column(TINYINT(unsigned=True))
    application_date = Column(Date)
    best_time_to_call_text = Column(String(20))
    church_referral_cb = Column(TINYINT(unsigned=True))
    city_text = Column(String(30))
    date_entered = Column(Date)
    date_of_birth_date = Column(Date)
    denomination = Column(String(50))
    deposit_cb = Column(TINYINT(unsigned=True))
    distance = Column(String(10))
    doctrine_cb = Column(TINYINT(unsigned=True))
    email_text = Column(String(180), unique=True)
    email_request_cb = Column(TINYINT(unsigned=True))
    explain_info_text = Column(Text)
    application_fee_dd = Column(String(3))
    feel_a_call_text = Column(String(40))
    finaid_rpt_sent_date = Column(Date)
    first_name_text = Column(String(40))
    folder_location = Column(INTEGER(unsigned=True))
    funnel_location = Column(String(2))
    grad_date_numtext = Column(INTEGER(unsigned=True), nullable=False, default=0)
    health_form_cb = Column(TINYINT(unsigned=True))
    hs_transcript_cb = Column(TINYINT(unsigned=True))
    facebook_text = Column(String(250))
    international_student_cb = Column(TINYINT(unsigned=True))
    isr_date = Column(Date)
    isr_is_valid_cb = Column(TINYINT(unsigned=True))
    kmbc_groups_dd = Column(String(35))
    lack_of_program_cb = Column(TINYINT(unsigned=True))
    last_call_date = Column(Date)
    last_contact_date = Column(Date)
    last_email_date = Column(Date)
    last_im_date = Column(Date)
    last_letter_date = Column(Date)
    last_name_text = Column(String(40))
    last_personal_visit_date = Column(Date)
    last_updated = Column(Date)
    letter_sent_date = Column(Date)
    marital_status_dd = Column(String(2))
    medical_release_cb = Column(TINYINT(unsigned=True))
    money_cb = Column(String(10))
    no_auto_email_cb = Column(TINYINT(unsigned=True))
    non_traditional_cb = Column(TINYINT(unsigned=True))
    number_of_visits_dd = Column(String(3))
    other_contact = Column(Text)
    other_admin_text = Column(Text)
    other_obstacle_cb = Column(TINYINT(unsigned=True))
    pastor_church_text = Column(String(50))
    pastor_church_cb = Column(TINYINT(unsigned=True))
    phone_text = Column(String(120))
    picture_cb = Column(TINYINT(unsigned=True))
    post_hs_transcript_cb = Column(TINYINT(unsigned=True))
    prospect_type = Column(String(2))
    provisional_acceptance_cb = Column(TINYINT(unsigned=True))
    queue_action_dd = Column(String(20))
    rec_date_of_review_date = Column(Date)
    recommendations_dd = Column(INTEGER(unsigned=True))
    rules_cb = Column(TINYINT(unsigned=True))
    sch_app_rcvd_cb = Column(TINYINT(unsigned=True))
    applied_semester_dd = Column(String(10))
    sex_dd = Column(String(2))
    special_interest_cb = Column(TINYINT(unsigned=True))
    ss_number_text = Column(String(11))
    state = Column(String(2))
    testimony_cb = Column(TINYINT(unsigned=True))
    toefl_dd = Column(String(10))
    final_transcript_cb = Column(TINYINT(unsigned=True))
    visit_1 = Column(TINYINT(unsigned=True))
    visit_2 = Column(TINYINT(unsigned=True))
    visit_3 = Column(TINYINT(unsigned=True))
    visited_campus_date = Column(Date)
    website_cb = Column(TINYINT(unsigned=True))
    work_app = Column(TINYINT(unsigned=True))
    applied_year_text = Column(INTEGER(unsigned=True))
    zipcode = Column(String(10))
    groupcode_numtext = Column(String(20))
    instructions_text = Column(Text)
    school_text = Column(String(150))
    downpayment_cb = Column(SmallInteger)  # tinyint(4)
    populi_id = Column(INTEGER)
    txt_optin_cb = Column(TINYINT(unsigned=True), default=0)
    primary_email_text = Column(String(180))

class ContactInfoTable(Base):
    __tablename__ = "contactinfotable"
    contactinfotableid = Column(BIGINT(unsigned=True), primary_key=True, autoincrement=True)
    contact_date = Column(Date)
    link_to_maininfotableid = Column(BIGINT(unsigned=True), nullable=False, default=0)
    notes = Column(Text)
    person = Column(String(10))
    type = Column(String(10))
    contact_time = Column(String(15))
